import type { Resource } from '../domain/resource'

export const resources: Resource[] = [
  {
    id: "r-001",
    name: "payments-api-prod",
    type: "EC2 Instance",
    provider: "AWS",
    region: "us-east-1",
    environment: "production",
    severity: "critical",
    owner: "payments",
    tags: ["pci", "api"],
    openIssues: 4,
  },
  {
    id: "r-002",
    name: "payments-db-prod",
    type: "RDS Database",
    provider: "AWS",
    region: "us-east-1",
    environment: "production",
    severity: "critical",
    owner: "payments",
    tags: ["pci", "database"],
    openIssues: 2,
  },
  {
    id: "r-003",
    name: "payments-s3-logs",
    type: "S3 Bucket",
    provider: "AWS",
    region: "us-east-1",
    environment: "production",
    severity: "high",
    owner: "payments",
    tags: ["pci", "logs"],
    openIssues: 1,
  },
  {
    id: "r-004",
    name: "auth-lambda-prod",
    type: "Lambda Function",
    provider: "AWS",
    region: "us-west-2",
    environment: "production",
    severity: "high",
    owner: "auth",
    tags: ["auth", "serverless"],
    openIssues: 0,
  },
  {
    id: "r-005",
    name: "legacy-payments-iam",
    type: "IAM Role",
    provider: "AWS",
    region: "us-east-1",
    environment: "staging",
    severity: "high",
    owner: "payments",
    tags: ["legacy", "iam"],
    openIssues: 7,
  },
  {
    id: "r-006",
    name: "analytics-bq-prod",
    type: "BigQuery Dataset",
    provider: "GCP",
    region: "us-central1",
    environment: "production",
    severity: "high",
    owner: "data",
    tags: ["analytics", "warehouse"],
    openIssues: 5,
  },
  {
    id: "r-007",
    name: "platform-gke-staging",
    type: "GKE Cluster",
    provider: "GCP",
    region: "us-central1",
    environment: "staging",
    severity: "medium",
    owner: "platform",
    tags: ["k8s", "compute"],
    openIssues: 3,
  },
  {
    id: "r-008",
    name: "data-pipeline-vm",
    type: "Compute Engine",
    provider: "GCP",
    region: "us-east1",
    environment: "staging",
    severity: "medium",
    owner: "data",
    tags: ["etl", "pipeline"],
    openIssues: 2,
  },
  {
    id: "r-009",
    name: "marketing-assets-gcs",
    type: "Cloud Storage",
    provider: "GCP",
    region: "europe-west1",
    environment: "development",
    severity: "low",
    owner: "marketing",
    tags: ["static", "web"],
    openIssues: 0,
  },
  {
    id: "r-010",
    name: "auth-keyvault-prod",
    type: "Key Vault",
    provider: "Azure",
    region: "eastus",
    environment: "production",
    severity: "critical",
    owner: "auth",
    tags: ["secrets", "auth"],
    openIssues: 1,
  },
  {
    id: "r-011",
    name: "platform-sql-staging",
    type: "SQL Database",
    provider: "Azure",
    region: "westeurope",
    environment: "staging",
    severity: "medium",
    owner: "platform",
    tags: ["database", "backend"],
    openIssues: 4,
  },
  {
    id: "r-012",
    name: "dev-sandbox-blob",
    type: "Blob Storage",
    provider: "Azure",
    region: "eastus",
    environment: "development",
    severity: "low",
    owner: "platform",
    tags: ["sandbox", "dev"],
    openIssues: 6,
  },
];
