import type { Resource } from '../domain/resource'

export const resources: Resource[] = [
  {
    id: 'resource-1',
    name: 'Payments API',
    type: 'API Gateway',
    provider: 'AWS',
    region: 'eu-west-1',
    environment: 'production',
    severity: 'critical',
    owner: 'Payments team',
    tags: ['payments', 'customer-facing'],
    openIssues: 3,
  },
  {
    id: 'resource-2',
    name: 'Order Processor',
    type: 'Container Service',
    provider: 'AWS',
    region: 'us-east-1',
    environment: 'staging',
    severity: 'high',
    owner: 'Orders team',
    tags: ['orders'],
    openIssues: 1,
  },
  {
    id: 'resource-3',
    name: 'Analytics Warehouse',
    type: 'Data Warehouse',
    provider: 'GCP',
    region: 'europe-west1',
    environment: 'development',
    severity: 'medium',
    owner: 'Data team',
    tags: ['analytics'],
    openIssues: 0,
  },
  {
    id: 'resource-4',
    name: 'Identity Service',
    type: 'Cloud Run Service',
    provider: 'GCP',
    region: 'us-central1',
    environment: 'production',
    severity: 'low',
    owner: 'Platform team',
    tags: ['identity', 'internal'],
    openIssues: 0,
  },
  {
    id: 'resource-5',
    name: 'Marketing Database',
    type: 'Database',
    provider: 'Azure',
    region: 'westeurope',
    environment: 'staging',
    severity: 'critical',
    owner: 'Marketing team',
    tags: ['marketing'],
    openIssues: 2,
  },
  {
    id: 'resource-6',
    name: 'Notification Queue',
    type: 'Message Queue',
    provider: 'Azure',
    region: 'northeurope',
    environment: 'development',
    severity: 'high',
    owner: 'Platform team',
    tags: ['notifications'],
    openIssues: 1,
  },
]
